#!/usr/bin/env python3
#
# Usage: get-options SUBJECT VERSION
#
# Print Angelix options for given subject and version

import os
import json
import sys

subject = sys.argv[1]


root = os.path.dirname(os.path.realpath(__file__))

options_file = os.path.join(root, 'options.json')

with open(options_file) as file:
    options = json.load(file)

for option in options[subject]:
    print(option)
