#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo "****"

test-updown () {
    diff -q <(${ANGELIX_RUN:-eval} ./updown $1) <($SCRIPT_DIR/../golden/updown $1) > /dev/null
}

case "$1" in
    1)
        test-updown  "1 98 200"
        ;;
    2)
        test-updown  "1 101 200"
        ;;
esac
